# Generated by Django 4.1 on 2024-06-23 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='jersey_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.AddField(
            model_name='player',
            name='college_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(default='N/A', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ign',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone_no',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='player',
            name='score_in_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_tournament_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='uid',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('qualifier', 'Qualifier'), ('final', 'Final')], max_length=20)),
                ('group', models.CharField(max_length=10)),
                ('team_score', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heff.team')),
            ],
            options={
                'unique_together': {('stage', 'group', 'team')},
            },
        ),
    ]
