# Generated by Django 4.1 on 2024-06-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0002_remove_player_date_of_birth_remove_player_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='heff.match')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='score_in_match',
        ),
        migrations.RemoveField(
            model_name='player',
            name='total_tournament_score',
        ),
        migrations.AlterField(
            model_name='player',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='ign',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='uid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.AddField(
            model_name='playerscore',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='heff.player'),
        ),
        migrations.AlterUniqueTogether(
            name='playerscore',
            unique_together={('player', 'match')},
        ),
    ]
