# Generated by Django 4.1 on 2024-06-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0003_match_playerscore_remove_player_score_in_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AlterUniqueTogether(
            name='playerscore',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='match',
        ),
        migrations.RemoveField(
            model_name='playerscore',
            name='player',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='PlayerScore',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
