# Generated by Django 4.1 on 2024-06-26 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='matchscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchscores', to='heff.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matchscores', to='heff.player')),
            ],
        ),
    ]
