# Generated by Django 4.1 on 2024-06-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0006_matchscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='matchscore',
        ),
    ]
