# Generated by Django 4.1 on 2024-06-26 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0007_delete_matchscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='heff.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='heff.team')),
            ],
            options={
                'unique_together': {('match', 'team')},
            },
        ),
    ]
