# Generated by Django 4.1 on 2024-06-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0008_matchscore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchScore',
        ),
    ]
