# Generated by Django 4.1 on 2024-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0009_delete_matchscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='match_pp',
            field=models.ManyToManyField(blank=True, related_name='teams', to='heff.match'),
        ),
    ]
