# Generated by Django 4.1 on 2024-06-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heff', '0010_team_match_pp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='match_pp',
            field=models.ManyToManyField(blank=True, related_name='teams_participated', to='heff.match'),
        ),
    ]
